config/routes.rb
Rails.application.routes.draw do
  resources :motos

  resources :model_names

end

app/models/model_name.rb
class ModelName < ActiveRecord::Base
end

app/models/moto.rb
class Moto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/model_names_controller.rb
class ModelNamesController < ApplicationController
  before_action :set_model_name, only: [:show, :edit, :update, :destroy]

  # GET /model_names
  # GET /model_names.json
  def index
    @model_names = ModelName.all
  end

  # GET /model_names/1
  # GET /model_names/1.json
  def show
  end

  # GET /model_names/new
  def new
    @model_name = ModelName.new
  end

  # GET /model_names/1/edit
  def edit
  end

  # POST /model_names
  # POST /model_names.json
  def create
    @model_name = ModelName.new(model_name_params)

    respond_to do |format|
      if @model_name.save
        format.html { redirect_to @model_name, notice: 'Model name was successfully created.' }
        format.json { render :show, status: :created, location: @model_name }
      else
        format.html { render :new }
        format.json { render json: @model_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /model_names/1
  # PATCH/PUT /model_names/1.json
  def update
    respond_to do |format|
      if @model_name.update(model_name_params)
        format.html { redirect_to @model_name, notice: 'Model name was successfully updated.' }
        format.json { render :show, status: :ok, location: @model_name }
      else
        format.html { render :edit }
        format.json { render json: @model_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /model_names/1
  # DELETE /model_names/1.json
  def destroy
    @model_name.destroy
    respond_to do |format|
      format.html { redirect_to model_names_url, notice: 'Model name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model_name
      @model_name = ModelName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_name_params
      params.require(:model_name).permit(:element, :etc)
    end
end

app/controllers/motos_controller.rb
class MotosController < ApplicationController
  before_action :set_moto, only: [:show, :edit, :update, :destroy]

  # GET /motos
  # GET /motos.json
  def index
    @motos = Moto.all
  end

  # GET /motos/1
  # GET /motos/1.json
  def show
  end

  # GET /motos/new
  def new
    @moto = Moto.new
  end

  # GET /motos/1/edit
  def edit
  end

  # POST /motos
  # POST /motos.json
  def create
    @moto = Moto.new(moto_params)

    respond_to do |format|
      if @moto.save
        format.html { redirect_to @moto, notice: 'Moto was successfully created.' }
        format.json { render :show, status: :created, location: @moto }
      else
        format.html { render :new }
        format.json { render json: @moto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motos/1
  # PATCH/PUT /motos/1.json
  def update
    respond_to do |format|
      if @moto.update(moto_params)
        format.html { redirect_to @moto, notice: 'Moto was successfully updated.' }
        format.json { render :show, status: :ok, location: @moto }
      else
        format.html { render :edit }
        format.json { render json: @moto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motos/1
  # DELETE /motos/1.json
  def destroy
    @moto.destroy
    respond_to do |format|
      format.html { redirect_to motos_url, notice: 'Moto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moto
      @moto = Moto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moto_params
      params.require(:moto).permit(:marque, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/model_names_helper.rb
module ModelNamesHelper
end

app/helpers/motos_helper.rb
module MotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appname</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/model_names/_form.html.erb
<%= form_for(@model_name) do |f| %>
  <% if @model_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model_name.errors.count, "error") %> prohibited this model_name from being saved:</h2>

      <ul>
      <% @model_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :element %><br>
    <%= f.text_field :element %>
  </div>
  <div class="field">
    <%= f.label :etc %><br>
    <%= f.text_field :etc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/model_names/edit.html.erb
<h1>Editing model_name</h1>

<%= render 'form' %>

<%= link_to 'Show', @model_name %> |
<%= link_to 'Back', model_names_path %>

app/views/model_names/index.html.erb
<h1>Listing model_names</h1>

<table>
  <thead>
    <tr>
      <th>Element</th>
      <th>Etc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @model_names.each do |model_name| %>
      <tr>
        <td><%= model_name.element %></td>
        <td><%= model_name.etc %></td>
        <td><%= link_to 'Show', model_name %></td>
        <td><%= link_to 'Edit', edit_model_name_path(model_name) %></td>
        <td><%= link_to 'Destroy', model_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model name', new_model_name_path %>

app/views/model_names/new.html.erb
<h1>New model_name</h1>

<%= render 'form' %>

<%= link_to 'Back', model_names_path %>

app/views/model_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Element:</strong>
  <%= @model_name.element %>
</p>

<p>
  <strong>Etc:</strong>
  <%= @model_name.etc %>
</p>

<%= link_to 'Edit', edit_model_name_path(@model_name) %> |
<%= link_to 'Back', model_names_path %>

app/views/motos/_form.html.erb
<%= form_for(@moto) do |f| %>
  <% if @moto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moto.errors.count, "error") %> prohibited this moto from being saved:</h2>

      <ul>
      <% @moto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marque %><br>
    <%= f.text_field :marque %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/motos/edit.html.erb
<h1>Editing moto</h1>

<%= render 'form' %>

<%= link_to 'Show', @moto %> |
<%= link_to 'Back', motos_path %>

app/views/motos/index.html.erb
<h1>Listing motos</h1>

<table>
  <thead>
    <tr>
      <th>Marque</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @motos.each do |moto| %>
      <tr>
        <td><%= moto.marque %></td>
        <td><%= moto.description %></td>
        <td><%= link_to 'Show', moto %></td>
        <td><%= link_to 'Edit', edit_moto_path(moto) %></td>
        <td><%= link_to 'Destroy', moto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Moto', new_moto_path %>

app/views/motos/new.html.erb
<h1>New moto</h1>

<%= render 'form' %>

<%= link_to 'Back', motos_path %>

app/views/motos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marque:</strong>
  <%= @moto.marque %>
</p>

<p>
  <strong>Description:</strong>
  <%= @moto.description %>
</p>

<%= link_to 'Edit', edit_moto_path(@moto) %> |
<%= link_to 'Back', motos_path %>